### ISSUE TITLE
阻塞获取

### ISSUE THREAD

**Issue by lizhipeng1** [cmlbeliever/distribute-lock#2]
如果获取所失败以后需要，阻塞当前线程 重复获取锁，那么有什么好的方案么

**Comment by cmlbeliever** [comment]
你可以通过AbstractDefaultDistributeLockService自定义实现。通过LockSupport进行线程阻塞
一般业务不需要你这种方式的吧？获取不到锁就说明正在处理，为什么还要等待呢？

**Comment by lizhipeng1** [comment]
ok
